### ISSUE TITLE
Installation instruction on Mac

### ISSUE THREAD

**Issue by noguxun** [fastly/fastlyctl#10]
Found permission problems to install it on macOS Catalina
After googled for a while, finally installed it successfully with below command

sudo gem install fastlyctl -n /usr/local/bin

I think it worth to be documented in the ReadMe.

**Comment by smaeda-ks** [comment]
That's most likely because you're using the system's default Ruby environment and you can't perform user install there. General speaking, the use of `sudo` with gem install is not really recommended for many reasons. I'd suggest you set up one of the version manager tools out there such as [rbenv](https://github.com/rbenv/rbenv) so you won't break your system's core files.

**Comment by carbon198** [comment]
I agree with @smaeda-ks. If you have to install with sudo, use a ruby environment manager instead. rbenv or rvm are both good options.
